version: 2.1
orbs:
  cypress: cypress-io/cypress@11.2.0
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node18.6.0-chrome105-ff104"
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          executor: with-chrome
          browser: chrome
          post-steps:
            - run: ls
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: cypress/screenshots