# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@11.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  - cypress/install:
      build: 'npm ci' # run a custom app build step
  - cypress/lint:
      requires:
        - cypress/install
      lint: 'npm run lint'
  - cypress/run:
      requires:
        - cypress/install
        - cypress/lint
      record: true # record results with Cypress Cloud
      parallel: true # split all specs across machines
      parallelism: 4 # use 4 CircleCI machines to finish quickly
      group: 'all tests' # name this group "all tests" on the dashboard
      start: 'npm run test' # start server before running tests

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  cypress-tests-workflow:
    jobs:
      - cypress/run
